# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('core/assets/vis-network.min.js', 'assets'),
        *collect_data_files('certifi'),
    ],
    hiddenimports=[
        'fitz',
        'openai',
        'pydantic',
        'pydantic.deprecated.decorator',
        'customtkinter',
        'tkinterdnd2',
        'dotenv',
        'PIL',
        'PIL._tkinter_finder',
        'certifi',
        'httpx',
        'httpcore',
        'h11',
        'anyio',
        'app',
        'app.main_window',
        'app.services',
        'core',
        'core.extractor',
        'core.knowledge_graph',
        'core.pdf_reader',
        'core.html_renderer',
        'core.cli',
        'gui',
        'gui.theme',
        'gui.sidebar',
        'gui.toast',
        'gui.widgets',
        'gui.pages',
        'gui.pages.input_page',
        'gui.pages.output_page',
        'gui.pages.settings_page',
        'gui.pages.results_page',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['pyi_rth_utf8.py'],
    excludes=[
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'tensorflow',
        'torch',
        'tkinter.test',
        'unittest',
        'test',
        'setuptools',
        'pip',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='multimodal-viz',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[
        'vcruntime140.dll',
        'python3*.dll',
        '*.pyd',
    ],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='knowledge_graph.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=['vcruntime140.dll', 'python3*.dll', '*.pyd'],
    name='multimodal-viz',
)
